"""change type of weight to float from int

Revision ID: 320f157226c3
Revises: 57420af725d5
Create Date: 2023-07-05 18:39:41.922045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320f157226c3'
down_revision = '57420af725d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
