"""add weight to food schema

Revision ID: 64b9605ebd68
Revises: eb2a94b58029
Create Date: 2023-07-06 13:45:22.124195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b9605ebd68'
down_revision = 'eb2a94b58029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_g', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('weight_g')

    # ### end Alembic commands ###
