"""add food schema with relationship to cat

Revision ID: c0ce37e35541
Revises: 320f157226c3
Create Date: 2023-07-06 12:54:30.986482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ce37e35541'
down_revision = '320f157226c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavour', sa.String(length=24), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('packaging', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_flavour'), ['flavour'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_packaging'), ['packaging'], unique=False)

    op.create_table('cat_food',
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cat.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat_food')
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_packaging'))
        batch_op.drop_index(batch_op.f('ix_food_flavour'))
        batch_op.drop_index(batch_op.f('ix_food_age'))

    op.drop_table('food')
    # ### end Alembic commands ###
