"""add wet or dry propery to food

Revision ID: eb2a94b58029
Revises: c0ce37e35541
Create Date: 2023-07-06 13:38:27.410783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2a94b58029'
down_revision = 'c0ce37e35541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wet_or_dry', sa.String(length=8), nullable=True))
        batch_op.create_index(batch_op.f('ix_food_wet_or_dry'), ['wet_or_dry'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_wet_or_dry'))
        batch_op.drop_column('wet_or_dry')

    # ### end Alembic commands ###
